crud/urls.py
from django.urls import path
from crud import views

app_name = 'crud'

urlpatterns = [
    path('', views.ClienteLists.as_view(), name='list'),
    path('create/', views.ClienteCreate.as_view(), name='create'),
    path('update/<int:pk>/', views.ClienteUpdate.as_view(), name='update'),
    path('detail/<int:pk>/', views.ClienteDetail.as_view(), name='detail'),
    path('delete/<int:pk>/', views.ClienteDelete.as_view(), name='delete'),
  
]

projetoCrud/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crud.urls'))
]

crud/models.py
from django.db import models

# Create your models here.

class Cliente(models.Model):
    nome = models.CharField(max_length=30)
    idade = models.IntegerField(blank=True, null=True)
    
    def __str__(self):
        return self.nome

crud/forms.py
from dataclasses import field
from socket import fromshare
from django import forms 
from crud.models import Cliente

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = '__all__'

crud/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from crud.models import Cliente

# Create your views here.

class ClienteLists(ListView):
    model = Cliente
    queryset = Cliente.objects.all()
    
class ClienteCreate(CreateView):
    model = Cliente
    fields = '__all__'
    success_url = reverse_lazy('crud:list')
    
class ClienteUpdate(UpdateView):
    model = Cliente
    fields = '__all__'
    success_url = reverse_lazy('crud:list')
    
class ClienteDetail(DetailView):
    queryset = Cliente.objects.all()

class ClienteDelete(DeleteView):
    queryset = Cliente.objects.all()
    success_url = reverse_lazy('crud:list')
    
    
    
    
    

templates/crud/cliente_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Apagar cliente</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h1>Tem certeza que deseja apagar o cliente '{{ object.nome }}'?</h1>
        <form action="." method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Sim, tenho certeza</button>
            <button type="button" class="btn btn-secondary" onclick="location.href = '{% url 'crud:list' %}'">Não quero apagar mais</button>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/crud/cliente_detail.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Visualizar cliente</title>
    
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <button type="button" class="btn btn-primary" onclick="location.href = '{% url 'crud:list' %}'">Voltar para a lista</button>
        <br><br>
        <h2>Detalhes do Cliente</h2>
        <br>
        <div class="row">
            <div class="col-md-6">
                <h4>Nome:</h4>
                <p>{{ object.nome }}</p>
            </div>
            <div class="col-md-6">
                <h4>Idade:</h4>
                <p>{{ object.idade }}</p>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/crud/cliente_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criar cliente</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h1>Inserindo cadastro de cliente</h1>
        <form method="post" action=".">

            {% csrf_token %}
            <div class="form-group">
                {{ form.nome.label_tag }}
                {{ form.nome }}
            </div>
            
            <div class="form-group">
                {{ form.idade.label_tag }}
                {{ form.idade }}
            </div>

            <button type="submit" class="btn btn-primary">Salvar</button>
            <button type="reset" class="btn btn-secondary" onclick="location.href = '{% url 'crud:list' %}'">Cancelar</button>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/crud/cliente_list.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Clientes</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
    
        body {
            padding: 20px;
        }
        .action-links {
            margin-left: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1 class="mt-5">Lista de Clientes</h1>
        <a class="btn btn-success mb-3" href="{% url 'crud:create' %}">Criar Novo Cliente</a>
        <ul class="list-group">
            {% for cliente in object_list %}
            <li class="list-group-item">
                <div class="d-flex justify-content-between align-items-center">
                    <span>{{ cliente.nome }}</span>
                    <div class="action-links">
                        <a class="btn btn-primary btn-sm" href="{% url 'crud:update' pk=cliente.id %}">Editar</a>
                        <a class="btn btn-info btn-sm" href="{% url 'crud:detail' pk=cliente.id %}">Visualizar</a>
                        <a class="btn btn-danger btn-sm" href="{% url 'crud:delete' pk=cliente.id %}">Apagar</a>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>